version: '3.8'

services:
  db:
    profiles: [ "api", "migration" ]
    image: postgres:15.7-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    profiles: [ "pgadmin" ]
    build:
      context: ./pgadmin/
      args:
        DB_HOST: db
        DB_PORT: ${DB_PORT}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_started
    environment:
      - DB_HOST=db
    env_file:
      - ./.env

  redis:
    profiles: [ "api" ]
    image: redis:7.0.15-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    profiles: [ "api" ]
    restart: unless-stopped
    ports:
      - 8000:8000
    build: ./
    volumes:
      - ./files:/app/files
      - static_value:/app/app/static/
      - ./logs:/app/logs
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - API_HOST=0
      - API_PORT=8000
      - LOG_PATH=/app/logs/web.log
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    entrypoint: /app/scripts/backend-start.sh

  migration:
    profiles: [ "migration" ]
    restart: on-failure
    build: ./
    environment:
      - DB_HOST=db
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    entrypoint: /app/scripts/migration-start.sh

  worker:
    profiles: [ "api" ]
    restart: unless-stopped
    build:
      dockerfile: worker.Dockerfile
    volumes:
      - ./files:/app/files
      - ./logs:/app/logs
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - LOG_PATH=/app/logs/worker.log
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    entrypoint: /app/scripts/worker-start.sh

  nginx:
    profiles: [ "nginx" ]
    image: nginx:1.25.4-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
    depends_on:
      web:
        condition: service_started

volumes:
  db_data:
  pgadmin_data:
  redis_data:
  static_value:
