- title: Профили добычи/закачки
  path: profile
  description: Распределение добычи/закачки по пластам, построенное<ul><li>на последний
    ненулевой МЭР</li><li>на последнее информативное ОПП</li></ul>
- title: Количество ОПП за год
  path: opp_per_year
  description: Количество ОПП за год:<ul><li>общее число исследований</li><li>число
    охваченных скважин</li></ul>
- title: Потери нефти по базе ГТМ ППД
  path: inj_loss
  loss_mode:
  - text: --Выберите режим выгрузки--
    value: --
    selected: true
  - text: Qн на начало периода
    value: first_rate
    selected: false
  - text: Максимальный Qн
    value: max_rate
    selected: false
  description: Потери дебита нефти по факторам дебита жидкости и обводненности:<ul>
    <li><b>Qн на начало периода</b> - начальная точка соответствует первому ненулевому МЭР</li>
    <li><b>максимальный Qн</b> - начальная точка соответствует МЭР с максимальным Qн</li>
    <li>конечная точка соответствует последней дате интервала</li></ul>
- title: Эффект ГТМ ППД по матрице
  path: matrix
  excludes:
  - text: --Выберите исключаемые ГТМ НФ--
    value: --
    selected: false
  - text: ЗБС
    value: ЗБС
    selected: true
  - text: ВНС
    value: ВНС
    selected: true
  - text: ПДГ
    value: ПДГ
    selected: true
  - text: ОРЭ
    value: ОРЭ
    selected: true
  - text: ГРП
    value: ГРП
    selected: true
  - text: ВБД
    value: ВБД
    selected: true
  - text: ИДФ
    value: ИДФ
    selected: true
  - text: Приобщение
    value: Приобщение
    selected: true
  - text: Дострел
    value: Дострел
    selected: false
  - text: ОПЗ
    value: ОПЗ
    selected: false
  - text: Перестрел
    value: Перестрел
    selected: false
  - text: ИДН
    value: ИДН
    selected: false
  - text: РИР
    value: РИР
    selected: false
  description: Эффект ГТМ ППД по матрице:<ul><li><b>базовый период</b> - число месяцев до даты ГТМ ППД
    </li><li><b>прогнозный период</b> - число месяцев после даты ГТМ ППД (включительно)</li>
    <li><b>на дату МЭР</b> - отчетный период формирования матрицы</li></ul>
- title: Потери нефти по НФ
  path: oil_loss
  loss_mode:
  - text: --Выберите режим выгрузки--
    value: --
    selected: true
  - text: Qн на начало периода
    value: first_rate
    selected: false
  - text: Максимальный Qн
    value: max_rate
    selected: false
  description: Потери дебита нефти по факторам дебита жидкости и обводненности:<ul>
    <li><b>Qн на начало периода</b> - начальная точка соответствует первому ненулевому МЭР</li>
    <li><b>максимальный Qн</b> - начальная точка соответствует МЭР с максимальным Qн</li>
    <li>конечная точка соответствует последней дате интервала</li></ul>
- title: Отчеты ФНВ
  path: fnv
  min_radius: 30
  alternative: true
  fields:
  - text: --Выберите месторождение--
    value: --
    selected: true
  - text: --Все месторождения--
    value: 0
    selected: false
  description: Фронт нагнетаемой воды
