from .base import BaseLoader
from .csv_loader import CsvLoader
from .field_replace import FieldReplaceLoader
from .gtm_replace import GtmReplaceLoader
from .inj_well_database import InjWellDatabaseLoader
from .layer_replace import LayerReplaceLoader
from .monthly_report import MonthlyReportLoader
from .neighborhood import NeighborhoodLoader
from .new_strategy_inj import NewStrategyInjLoader
from .new_strategy_oil import NewStrategyOilLoader
from .reservoir_replace import ReservoirReplaceLoader
from .well_profile import WellProfileLoader
from .well_test import WellTestLoader
