"""Initial migration

Revision ID: 04add837fd0f
Revises: 
Create Date: 2023-04-24 15:19:59.761125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04add837fd0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthlyreport',
    sa.Column('field', sa.String(length=50), nullable=False),
    sa.Column('well_name', sa.String(length=10), nullable=False),
    sa.Column('cid', sa.String(length=20), nullable=False),
    sa.Column('cid_all', sa.String(length=50), nullable=False),
    sa.Column('dat_rep', sa.Date(), nullable=False),
    sa.Column('oil_v', sa.Float(), nullable=False),
    sa.Column('water_v', sa.Float(), nullable=False),
    sa.Column('water', sa.Float(), nullable=False),
    sa.Column('days', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field', 'well_name', 'cid', 'dat_rep', name='field-well_name-cid-dat_rep')
    )
    op.create_table('wellprofile',
    sa.Column('field', sa.String(length=50), nullable=True),
    sa.Column('uwi', sa.String(length=10), nullable=True),
    sa.Column('well_name', sa.String(length=10), nullable=True),
    sa.Column('well_type', sa.String(length=50), nullable=True),
    sa.Column('cid_all', sa.String(length=50), nullable=True),
    sa.Column('layer', sa.String(length=100), nullable=True),
    sa.Column('rec_date', sa.Date(), nullable=False),
    sa.Column('top', sa.Float(), nullable=False),
    sa.Column('bottom', sa.Float(), nullable=False),
    sa.Column('abstop', sa.Float(), nullable=True),
    sa.Column('absbotm', sa.Float(), nullable=True),
    sa.Column('diff_absorp', sa.Float(), nullable=True),
    sa.Column('tot_absorp', sa.Float(), nullable=True),
    sa.Column('liq_rate', sa.Float(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uwi-rec_date', 'wellprofile', ['uwi', 'rec_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uwi-rec_date', table_name='wellprofile')
    op.drop_table('wellprofile')
    op.drop_table('monthlyreport')
    # ### end Alembic commands ###
