"""Initial migration

Revision ID: 5cf3dc6f88fd
Revises: 
Create Date: 2023-04-03 18:12:35.205019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cf3dc6f88fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthlyreport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=50), nullable=False),
    sa.Column('well_name', sa.String(length=10), nullable=False),
    sa.Column('cid', sa.String(length=20), nullable=False),
    sa.Column('cid_all', sa.String(length=50), nullable=False),
    sa.Column('dat_rep', sa.Date(), nullable=False),
    sa.Column('oil_v', sa.Float(), nullable=False),
    sa.Column('water_v', sa.Float(), nullable=False),
    sa.Column('water', sa.Float(), nullable=False),
    sa.Column('days', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field', 'well_name', 'cid', 'dat_rep', name='field-well_name-cid-date_stamp')
    )
    op.create_table('wellprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=50), nullable=False),
    sa.Column('uwi', sa.String(length=10), nullable=False),
    sa.Column('well_name', sa.String(length=10), nullable=False),
    sa.Column('well_type', sa.String(length=50), nullable=True),
    sa.Column('rec_date', sa.Date(), nullable=False),
    sa.Column('cid_all', sa.String(length=50), nullable=False),
    sa.Column('layer', sa.String(length=100), nullable=True),
    sa.Column('top', sa.Float(), nullable=False),
    sa.Column('bottom', sa.Float(), nullable=False),
    sa.Column('abstop', sa.Float(), nullable=True),
    sa.Column('absbotm', sa.Float(), nullable=True),
    sa.Column('diff_absorp', sa.Float(), nullable=True),
    sa.Column('tot_absorp', sa.Float(), nullable=True),
    sa.Column('liq_rate', sa.Float(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wellprofile', schema=None) as batch_op:
        batch_op.create_index('uwi-date_stamp', ['uwi', 'rec_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wellprofile', schema=None) as batch_op:
        batch_op.drop_index('uwi-date_stamp')

    op.drop_table('wellprofile')
    op.drop_table('monthlyreport')
    # ### end Alembic commands ###
