"""Initial migration

Revision ID: 86d7145ffcc8
Revises: 
Create Date: 2023-06-16 14:43:22.828959

"""
from alembic import op
import sqlalchemy as sa
import app.core.migration_types


# revision identifiers, used by Alembic.
revision = '86d7145ffcc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fieldreplace',
    sa.Column('group', sa.String(length=20), nullable=False),
    sa.Column('replace', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('pattern', sa.String(length=150), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layerreplace',
    sa.Column('group', sa.String(length=20), nullable=False),
    sa.Column('replace', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monthlyreport',
    sa.Column('field', app.core.migration_types.FieldType(length=50), nullable=False),
    sa.Column('well_name', app.core.migration_types.WellType(length=10), nullable=False),
    sa.Column('cid_all', app.core.migration_types.MultiResevoirType(length=200), nullable=False),
    sa.Column('cid', app.core.migration_types.ResevoirType(length=100), nullable=False),
    sa.Column('oil_v', sa.Float(), nullable=False),
    sa.Column('water_v', sa.Float(), nullable=False),
    sa.Column('water', sa.Float(), nullable=False),
    sa.Column('days', sa.Float(), nullable=False),
    sa.Column('dat_rep', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field', 'well_name', 'cid', 'dat_rep', name='field-well_name-cid-dat_rep')
    )
    op.create_table('reservoirreplace',
    sa.Column('group', sa.String(length=20), nullable=False),
    sa.Column('replace', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('pattern', sa.String(length=150), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wellprofile',
    sa.Column('field', app.core.migration_types.FieldType(length=50), nullable=False),
    sa.Column('well_name', app.core.migration_types.WellType(length=10), nullable=False),
    sa.Column('cid_all', app.core.migration_types.MultiResevoirType(length=200), nullable=False),
    sa.Column('cid_layer', app.core.migration_types.ResevoirType(length=100), nullable=True),
    sa.Column('layer', app.core.migration_types.MultiLayerType(length=100), nullable=True),
    sa.Column('uwi', sa.String(length=10), nullable=False),
    sa.Column('well_type', sa.String(), nullable=True),
    sa.Column('top', sa.Float(), nullable=False),
    sa.Column('bottom', sa.Float(), nullable=False),
    sa.Column('abstop', sa.Float(), nullable=True),
    sa.Column('absbotm', sa.Float(), nullable=True),
    sa.Column('diff_absorp', sa.Float(), nullable=True),
    sa.Column('tot_absorp', sa.Float(), nullable=True),
    sa.Column('liq_rate', sa.Float(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('rec_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uwi-rec_date', 'wellprofile', ['uwi', 'rec_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uwi-rec_date', table_name='wellprofile')
    op.drop_table('wellprofile')
    op.drop_table('reservoirreplace')
    op.drop_table('monthlyreport')
    op.drop_table('layerreplace')
    op.drop_table('fieldreplace')
    # ### end Alembic commands ###
