- title: Профили добычи/закачки
  path: profile
  description: Профили добычи/закачки для ТСРМ
- title: Количество ОПП за год
  path: opp_per_year
  description: Количество ОПП по годам для ТСРМ
- title: Потери нефти по базе ГТМ ППД
  path: inj_loss
  loss_mode:
  - text: --Выберите режим выгрузки--
    value: --
    selected: true
  - text: Qн на начало периода
    value: first_rate
    selected: false
  - text: Максимальный Qн
    value: max_rate
    selected: false
  description: Потери Qн по округе нагнетательных скважин
- title: Эффект ГТМ ППД по матрице
  path: matrix
  excludes:
  - text: --Выберите исключаемые ГТМ НФ--
    value: --
    selected: false
  - text: ЗБС
    value: ЗБС
    selected: true
  - text: ВНС
    value: ВНС
    selected: true
  - text: ПДГ
    value: ПДГ
    selected: true
  - text: ОРЭ
    value: ОРЭ
    selected: true
  - text: ГРП
    value: ГРП
    selected: true
  - text: ВБД
    value: ВБД
    selected: true
  - text: ИДФ
    value: ИДФ
    selected: true
  - text: Приобщение
    value: Приобщение
    selected: true
  - text: Дострел
    value: Дострел
    selected: false
  - text: ОПЗ
    value: ОПЗ
    selected: false
  - text: Реперфорация
    value: Реперфорация
    selected: false
  - text: ИДН
    value: ИДН
    selected: false
  - text: РИР
    value: РИР
    selected: false
  description: Эффект ГТМ ППД по матрице для ОУЗ
- title: Потери нефти по НФ
  path: oil_loss
  loss_mode:
  - text: --Выберите режим выгрузки--
    value: --
    selected: true
  - text: Qн на начало периода
    value: first_rate
    selected: false
  - text: Максимальный Qн
    value: max_rate
    selected: false
  description: Потери Qн по факторам (аналог PackagesRelease)
- title: Контуры ФНВ
  path: fnv
  min_radius: 30
  alternative: true
  fields:
  - text: --Выберите месторождение--
    value: --
    selected: true
  - text: --Все месторождения--
    value: 0
    selected: false
  description: Фронт нагнетаемой воды для загрузки в РН-КИН
- title: Шаблон для матбаланса (РН-КИН)
  path: matbal
  alternative: false
  fields:
  - text: --Выберите месторождение--
    value: --
    selected: true
  reservoirs:
  - text: --Выберите объект(ы)--
    value: --
    selected: false
  wells: Список скважин
  measurements: Замеры Рпл
  description: Шаблон для автоадаптации параметров матбаланса
- title: Пролонгация эффекта ППД по ХВ
  path: prolong
  expected: ДД план
  actual: ДД факт
  interpolation:
  - text: Метод PCHIP
    value: pchip
    selected: true
  - text: Алгоритм Акима
    value: akima
    selected: false
  - text: Кубический сплайн
    value: cubic
    selected: false
  description: Пролонгация эффекта ППД (факт+план)
- title: Выгрузка исходников для ММБ (Julia)
  path: mmb
  alternative: true
  tank: Параметры блоков
  description: Исходники для работы ММБ (добыча, закачка, замеры Рпл и т.д.)
- title: Выгрузка для компенсаций
  path: compensation
  description: Выгрузка для сводной таблицы с целевыми компенсациями
- title: Отчет по ГДИС
  path: well_test
  file: Отчет Сиам
  gtm_period: Период ГТМ (мес)
  gdis_period: Период ГДИС (лет)
  radius: Радиус
  description: Выгрузка для отчета по ГДИС (аналитика, ГТМ и т.д.)
