groups:
  ОПП:
    icon: bi-bar-chart-steps
    color: '#F6D106'
    order: 0
    text_dark: true
  Потери:
    icon: bi-exclamation-diamond-fill
    color: '#EF6B01'
    order: 1
    text_dark: true
  ППД:
    icon: bi-water
    color: '#475B79'
    order: 2
  ГДИС:
    icon: bi-eye-fill
    color: '#C20937'
    order: 3
  Моделирование:
    icon: bi-diagram-3-fill
    color: '#3D464A'
    order: 4
items:
- title: Профили добычи/закачки
  path: profile
  group: ОПП
  icon: bi-bar-chart-line-fill
  description: Профили добычи/закачки для ТСРМ
  tables:
    required:
    - МЭР
    - ОПП
- title: Количество ОПП за год
  path: opp_per_year
  group: ОПП
  icon: bi-calendar-check-fill
  description: Количество ОПП по годам для ТСРМ
- title: Потери нефти по базе ГТМ ППД
  path: inj_loss
  group: Потери
  icon: bi-droplet-fill
  loss_mode:
  - text: --Выберите режим выгрузки--
    value: --
    selected: true
  - text: Qн на начало периода
    value: first_rate
    selected: false
  - text: Максимальный Qн
    value: max_rate
    selected: false
  neighbs_from_ns_ppd: false
  description: Потери Qн по округе нагнетательных скважин
  tables:
    required:
    - МЭР
    - База ГТМ ППД
    optional:
    - НС ППД
    - Округа
    - НС НФ
- title: Эффект ГТМ ППД по матрице
  path: matrix
  group: Потери
  icon: bi-grid-3x3-gap-fill
  excludes:
  - text: --Выберите исключаемые ГТМ НФ--
    value: --
    selected: false
  - text: ЗБС
    value: ЗБС
    selected: true
  - text: ВНС
    value: ВНС
    selected: true
  - text: ПДГ
    value: ПДГ
    selected: true
  - text: ОРЭ
    value: ОРЭ
    selected: true
  - text: ГРП
    value: ГРП
    selected: true
  - text: ВБД
    value: ВБД
    selected: true
  - text: ИДФ
    value: ИДФ
    selected: true
  - text: Приобщение
    value: Приобщение
    selected: true
  - text: Дострел
    value: Дострел
    selected: false
  - text: ОПЗ
    value: ОПЗ
    selected: false
  - text: Реперфорация
    value: Реперфорация
    selected: false
  - text: ИДН
    value: ИДН
    selected: false
  - text: РИР
    value: РИР
    selected: false
  wells: Список скважин
  description: Эффект ГТМ ППД по матрице для ОУЗ
  tables:
    required:
    - МЭР
    - НС НФ
    - НС ППД
- title: Потери нефти по НФ
  path: oil_loss
  group: Потери
  icon: bi-pie-chart-fill
  loss_mode:
  - text: --Выберите режим выгрузки--
    value: --
    selected: true
  - text: Qн на начало периода
    value: first_rate
    selected: false
  - text: Максимальный Qн
    value: max_rate
    selected: false
  description: Потери Qн по факторам (аналог PackagesRelease)
  tables:
    required:
    - МЭР
    optional:
    - НС НФ
- title: Контуры ФНВ
  path: fnv
  group: ОПП
  icon: bi-bullseye
  min_radius: 30
  alternative: true
  fields:
  - text: --Выберите месторождение--
    value: --
    selected: true
  - text: --Все месторождения--
    value: 0
    selected: false
  description: Фронт нагнетаемой воды для загрузки в РН-КИН
- title: Шаблон для матбаланса (РН-КИН)
  path: matbal
  group: Моделирование
  icon: bi-calculator-fill
  alternative: false
  fields:
  - text: --Выберите месторождение--
    value: --
    selected: true
  reservoirs:
  - text: --Выберите объект(ы)--
    value: --
    selected: false
  wells: Список скважин
  measurements: Замеры Рпл
  description: Шаблон для автоадаптации параметров матбаланса
- title: Пролонгация эффекта ППД по ХВ
  path: prolong
  group: ППД
  icon: bi-graph-up-arrow
  expected: ДД план
  actual: ДД факт
  interpolation:
  - text: --Все методы--
    value: all
    selected: true
  - text: Метод PCHIP
    value: pchip
    selected: false
  - text: Алгоритм Акима
    value: akima
    selected: false
  - text: Кубический сплайн
    value: cubic
    selected: false
  description: Пролонгация эффекта ППД (факт+план)
- title: Выгрузка исходников для ММБ (Julia)
  path: mmb
  group: Моделирование
  icon: bi-hexagon
  alternative: true
  tank: Параметры блоков
  description: Исходники для работы ММБ (добыча, закачка, замеры Рпл и т.д.)
- title: Выгрузка для компенсаций
  path: compensation
  group: ППД
  icon: bi-arrow-repeat
  description: Выгрузка для сводной таблицы с целевыми компенсациями
- title: Отчет по ГДИС
  path: well_test
  group: ГДИС
  icon: bi-activity
  file: Отчет Сиам
  gtm_period: Период ГТМ (мес)
  gdis_period: Период ГДИС (лет)
  radius: Радиус
  description: Выгрузка для отчета по ГДИС (аналитика, ГТМ и т.д.)
  tables:
    required:
    - Аналитика ГДИС
    optional:
    - НС ППД
    - НС НФ
- title: Пересчет давления на ВНК
  path: owc_resp
  group: ГДИС
  icon: bi-speedometer2
  fields:
  - text: --Выберите месторождение--
    value: --
    selected: true
  reservoirs:
  - text: --Выберите объект--
    value: --
    selected: true
  well: Номер скважин
  pressure: Давление (атм)
  depth: Глубина (м)
  well_test:
  - text: --Выберите вид исследования--
    value: --
    selected: true
  - text: Hст
    value: static_level
    selected: false
  - text: Pпл
    value: pressure
    selected: false
  description: Пересчет давления на глубину с учетом инклинометрии скважины
