"""Add GTM type

Revision ID: 298793a8db2e
Revises: 3c352839b800
Create Date: 2024-10-07 18:06:39.166071

"""
from alembic import op
import sqlalchemy as sa
import app.infrastructure.db.migrations.types


# revision identifiers, used by Alembic.
revision = '298793a8db2e'
down_revision = '3c352839b800'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gtmreplace',
    sa.Column('group', sa.String(length=20), nullable=False),
    sa.Column('replace', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__gtmreplace')),
    schema='utils'
    )
    op.alter_column('newstrategyoil', 'gtm_name',
               existing_type=sa.VARCHAR(length=50),
               type_=app.infrastructure.db.migrations.types.GtmType(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('newstrategyoil', 'gtm_name',
               existing_type=app.infrastructure.db.migrations.types.GtmType(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_table('gtmreplace', schema='utils')
    # ### end Alembic commands ###
