"""First migration

Revision ID: 43d8ab9b3d7c
Revises: 
Create Date: 2024-01-08 16:06:29.433235

"""
from alembic import op
import sqlalchemy as sa
import app.infrastructure.db.migrations.types


# revision identifiers, used by Alembic.
revision = '43d8ab9b3d7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('injwelldatabase',
    sa.Column('field', app.infrastructure.db.migrations.types.FieldType(length=50), nullable=False),
    sa.Column('well', app.infrastructure.db.migrations.types.WellType(length=10), nullable=False),
    sa.Column('created_at', sa.Date(), server_default=sa.text('current_date'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__injwelldatabase')),
    sa.UniqueConstraint('field', 'well', name=op.f('uq__injwelldatabase__field'))
    )
    op.create_index(op.f('ix__injwelldatabase_field'), 'injwelldatabase', ['field'], unique=False)
    op.create_index(op.f('ix__injwelldatabase_well'), 'injwelldatabase', ['well'], unique=False)
    op.create_table('monthlyreport',
    sa.Column('field', app.infrastructure.db.migrations.types.FieldType(length=50), nullable=False),
    sa.Column('well_name', app.infrastructure.db.migrations.types.WellType(length=10), nullable=False),
    sa.Column('cid_all', app.infrastructure.db.migrations.types.MultiResevoirType(length=200), nullable=False),
    sa.Column('cid', app.infrastructure.db.migrations.types.ResevoirType(length=100), nullable=False),
    sa.Column('dat_rep', sa.Date(), nullable=False),
    sa.Column('oil', sa.Float(), nullable=False),
    sa.Column('oil_v', sa.Float(), nullable=False),
    sa.Column('water_v', sa.Float(), nullable=False),
    sa.Column('water', sa.Float(), nullable=False),
    sa.Column('days', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__monthlyreport')),
    sa.UniqueConstraint('field', 'well_name', 'cid', 'dat_rep', name=op.f('uq__monthlyreport__field'))
    )
    op.create_index(op.f('ix__monthlyreport_cid'), 'monthlyreport', ['cid'], unique=False)
    op.create_index(op.f('ix__monthlyreport_cid_all'), 'monthlyreport', ['cid_all'], unique=False)
    op.create_index(op.f('ix__monthlyreport_dat_rep'), 'monthlyreport', ['dat_rep'], unique=False)
    op.create_index(op.f('ix__monthlyreport_field'), 'monthlyreport', ['field'], unique=False)
    op.create_index(op.f('ix__monthlyreport_well_name'), 'monthlyreport', ['well_name'], unique=False)
    op.create_table('neighborhood',
    sa.Column('field', app.infrastructure.db.migrations.types.FieldType(length=50), nullable=False),
    sa.Column('reservoir', app.infrastructure.db.migrations.types.ResevoirType(length=100), nullable=False),
    sa.Column('well', app.infrastructure.db.migrations.types.WellType(length=10), nullable=False),
    sa.Column('neighbs', app.infrastructure.db.migrations.types.MultiWellType(length=100), nullable=False),
    sa.Column('created_at', sa.Date(), server_default=sa.text('current_date'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__neighborhood')),
    sa.UniqueConstraint('field', 'reservoir', 'well', name=op.f('uq__neighborhood__field'))
    )
    op.create_index(op.f('ix__neighborhood_field'), 'neighborhood', ['field'], unique=False)
    op.create_index(op.f('ix__neighborhood_reservoir'), 'neighborhood', ['reservoir'], unique=False)
    op.create_index(op.f('ix__neighborhood_well'), 'neighborhood', ['well'], unique=False)
    op.create_table('newstrategyinj',
    sa.Column('field', app.infrastructure.db.migrations.types.FieldType(length=50), nullable=False),
    sa.Column('well', app.infrastructure.db.migrations.types.WellType(length=10), nullable=False),
    sa.Column('reservoir', app.infrastructure.db.migrations.types.MultiSplitResevoirType(length=200), nullable=False),
    sa.Column('gtm_date', sa.Date(), nullable=False),
    sa.Column('gtm_description', sa.String(), nullable=False),
    sa.Column('oil_recovery', sa.Float(), nullable=True),
    sa.Column('effect_end', sa.Date(), nullable=True),
    sa.Column('gtm_group', sa.String(), nullable=True),
    sa.Column('oil_rate', sa.Float(), nullable=True),
    sa.Column('gtm_problem', sa.String(), nullable=False),
    sa.Column('reservoir_neighbs', app.infrastructure.db.migrations.types.MultiSplitResevoirType(length=200), nullable=True),
    sa.Column('neighbs', app.infrastructure.db.migrations.types.MultiWellType(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__newstrategyinj')),
    sa.UniqueConstraint('field', 'well', 'gtm_date', name=op.f('uq__newstrategyinj__field'))
    )
    op.create_index(op.f('ix__newstrategyinj_field'), 'newstrategyinj', ['field'], unique=False)
    op.create_index(op.f('ix__newstrategyinj_gtm_date'), 'newstrategyinj', ['gtm_date'], unique=False)
    op.create_index(op.f('ix__newstrategyinj_well'), 'newstrategyinj', ['well'], unique=False)
    op.create_table('newstrategyoil',
    sa.Column('field', app.infrastructure.db.migrations.types.FieldType(length=50), nullable=False),
    sa.Column('well', app.infrastructure.db.migrations.types.WellType(length=10), nullable=False),
    sa.Column('reservoir_before', app.infrastructure.db.migrations.types.MultiSplitResevoirType(length=200), nullable=False),
    sa.Column('reservoir_after', app.infrastructure.db.migrations.types.MultiSplitResevoirType(length=200), nullable=False),
    sa.Column('vnr_date', sa.Date(), nullable=False),
    sa.Column('gtm_name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__newstrategyoil')),
    sa.UniqueConstraint('field', 'well', 'vnr_date', name=op.f('uq__newstrategyoil__field'))
    )
    op.create_index(op.f('ix__newstrategyoil_field'), 'newstrategyoil', ['field'], unique=False)
    op.create_index(op.f('ix__newstrategyoil_vnr_date'), 'newstrategyoil', ['vnr_date'], unique=False)
    op.create_index(op.f('ix__newstrategyoil_well'), 'newstrategyoil', ['well'], unique=False)
    op.create_table('fieldreplace',
    sa.Column('group', sa.String(length=20), nullable=False),
    sa.Column('replace', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('pattern', sa.String(length=150), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__fieldreplace')),
    schema='utils'
    )
    op.create_table('layerreplace',
    sa.Column('group', sa.String(length=20), nullable=False),
    sa.Column('replace', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__layerreplace')),
    schema='utils'
    )
    op.create_table('reservoirreplace',
    sa.Column('group', sa.String(length=20), nullable=False),
    sa.Column('replace', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('pattern', sa.String(length=150), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__reservoirreplace')),
    schema='utils'
    )
    op.create_table('wellprofile',
    sa.Column('field', app.infrastructure.db.migrations.types.FieldType(length=50), nullable=False),
    sa.Column('well_name', app.infrastructure.db.migrations.types.WellType(length=10), nullable=False),
    sa.Column('cid_all', app.infrastructure.db.migrations.types.MultiResevoirType(length=200), nullable=False),
    sa.Column('cid_layer', app.infrastructure.db.migrations.types.ResevoirType(length=100), nullable=True),
    sa.Column('layer', app.infrastructure.db.migrations.types.MultiLayerType(length=100), nullable=True),
    sa.Column('rec_date', sa.Date(), nullable=False),
    sa.Column('uwi', sa.String(length=10), nullable=False),
    sa.Column('well_type', sa.String(), nullable=True),
    sa.Column('top', sa.Float(), nullable=False),
    sa.Column('bottom', sa.Float(), nullable=False),
    sa.Column('abstop', sa.Float(), nullable=True),
    sa.Column('absbotm', sa.Float(), nullable=True),
    sa.Column('diff_absorp', sa.Float(), nullable=True),
    sa.Column('tot_absorp', sa.Float(), nullable=True),
    sa.Column('liq_rate', sa.Float(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__wellprofile'))
    )
    op.create_index(op.f('ix__wellprofile_cid_all'), 'wellprofile', ['cid_all'], unique=False)
    op.create_index(op.f('ix__wellprofile_field'), 'wellprofile', ['field'], unique=False)
    op.create_index(op.f('ix__wellprofile_rec_date'), 'wellprofile', ['rec_date'], unique=False)
    op.create_index(op.f('ix__wellprofile_uwi'), 'wellprofile', ['uwi'], unique=False)
    op.create_index(op.f('ix__wellprofile_well_name'), 'wellprofile', ['well_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__wellprofile_well_name'), table_name='wellprofile')
    op.drop_index(op.f('ix__wellprofile_uwi'), table_name='wellprofile')
    op.drop_index(op.f('ix__wellprofile_rec_date'), table_name='wellprofile')
    op.drop_index(op.f('ix__wellprofile_field'), table_name='wellprofile')
    op.drop_index(op.f('ix__wellprofile_cid_all'), table_name='wellprofile')
    op.drop_table('wellprofile')
    op.drop_table('reservoirreplace', schema='utils')
    op.drop_table('layerreplace', schema='utils')
    op.drop_table('fieldreplace', schema='utils')
    op.drop_index(op.f('ix__newstrategyoil_well'), table_name='newstrategyoil')
    op.drop_index(op.f('ix__newstrategyoil_vnr_date'), table_name='newstrategyoil')
    op.drop_index(op.f('ix__newstrategyoil_field'), table_name='newstrategyoil')
    op.drop_table('newstrategyoil')
    op.drop_index(op.f('ix__newstrategyinj_well'), table_name='newstrategyinj')
    op.drop_index(op.f('ix__newstrategyinj_gtm_date'), table_name='newstrategyinj')
    op.drop_index(op.f('ix__newstrategyinj_field'), table_name='newstrategyinj')
    op.drop_table('newstrategyinj')
    op.drop_index(op.f('ix__neighborhood_well'), table_name='neighborhood')
    op.drop_index(op.f('ix__neighborhood_reservoir'), table_name='neighborhood')
    op.drop_index(op.f('ix__neighborhood_field'), table_name='neighborhood')
    op.drop_table('neighborhood')
    op.drop_index(op.f('ix__monthlyreport_well_name'), table_name='monthlyreport')
    op.drop_index(op.f('ix__monthlyreport_field'), table_name='monthlyreport')
    op.drop_index(op.f('ix__monthlyreport_dat_rep'), table_name='monthlyreport')
    op.drop_index(op.f('ix__monthlyreport_cid_all'), table_name='monthlyreport')
    op.drop_index(op.f('ix__monthlyreport_cid'), table_name='monthlyreport')
    op.drop_table('monthlyreport')
    op.drop_index(op.f('ix__injwelldatabase_well'), table_name='injwelldatabase')
    op.drop_index(op.f('ix__injwelldatabase_field'), table_name='injwelldatabase')
    op.drop_table('injwelldatabase')
    # ### end Alembic commands ###
