"""Add well test layer

Revision ID: dc34bf2c995f
Revises: f6abb8915582
Create Date: 2025-02-18 15:18:56.841216

"""
from alembic import op
import sqlalchemy as sa
import app.infrastructure.db.migrations.types


# revision identifiers, used by Alembic.
revision = 'dc34bf2c995f'
down_revision = 'f6abb8915582'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('welltest', sa.Column('layer', app.infrastructure.db.migrations.types.WellTestMultiLayerType(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('welltest', 'layer')
    # ### end Alembic commands ###
