"""Add well test

Revision ID: f6abb8915582
Revises: 298793a8db2e
Create Date: 2024-10-23 08:37:47.787363

"""
from alembic import op
import sqlalchemy as sa
import app.infrastructure.db.migrations.types


# revision identifiers, used by Alembic.
revision = 'f6abb8915582'
down_revision = '298793a8db2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('welltest',
    sa.Column('field', app.infrastructure.db.migrations.types.FieldType(length=50), nullable=False),
    sa.Column('well', app.infrastructure.db.migrations.types.WellType(length=10), nullable=False),
    sa.Column('reservoir', app.infrastructure.db.migrations.types.MultiSplitResevoirType(length=200), nullable=False),
    sa.Column('well_type', sa.String(), nullable=True),
    sa.Column('well_test', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('resp_owc', sa.Float(), nullable=True),
    sa.Column('oil_perm', sa.Float(), nullable=True),
    sa.Column('wat_perm', sa.Float(), nullable=True),
    sa.Column('liq_perm', sa.Float(), nullable=True),
    sa.Column('skin_factor', sa.Float(), nullable=True),
    sa.Column('prod_index', sa.Float(), nullable=True),
    sa.Column('frac_length', sa.Float(), nullable=True),
    sa.Column('reliability', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__welltest')),
    sa.UniqueConstraint('field', 'well', 'reservoir', 'well_test', 'end_date', name=op.f('uq__welltest__field'))
    )
    op.create_index(op.f('ix__welltest__end_date'), 'welltest', ['end_date'], unique=False)
    op.create_index(op.f('ix__welltest__field'), 'welltest', ['field'], unique=False)
    op.create_index(op.f('ix__welltest__reservoir'), 'welltest', ['reservoir'], unique=False)
    op.create_index(op.f('ix__welltest__well'), 'welltest', ['well'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__welltest__well'), table_name='welltest')
    op.drop_index(op.f('ix__welltest__reservoir'), table_name='welltest')
    op.drop_index(op.f('ix__welltest__field'), table_name='welltest')
    op.drop_index(op.f('ix__welltest__end_date'), table_name='welltest')
    op.drop_table('welltest')
    # ### end Alembic commands ###
