- description: Распределение добычи/закачки по пластам, построенное<ul><li>на последний
    ненулевой МЭР</li><li>на последнее информативное ОПП</li></ul>
  path: profile
  title: Профили добычи/закачки
- description: Потери дебита нефти по факторам дебита жидкости и обводненности:<ul><li>начальная
    точка соответствует первому ненулевому МЭР</li><li>конечная точка соответствует
    последней дате интервала</li></ul>
  loss_mode:
    options:
    - text: Qн на начало периода
      value: first_rate
    - text: Максимальный Qн
      value: max_rate
    selected: --Выберите режим выгрузки--
  path: oil_loss
  title: Потери по базе ГТМ ППД
- description: Количество ОПП за год:<ul><li>общее число исследований</li><li>число
    охваченных скважин</li></ul>
  path: opp_per_year
  title: Количество ОПП за год
