from .compensation import compensation_report
from .fnv import fnv_report
from .inj_loss import inj_loss_report
from .matbal import matbal_report
from .matrix import matrix_report
from .mmb import mmb_report
from .oil_loss import oil_loss_report
from .opp_per_year import opp_per_year_report
from .profile import profile_report
from .prolong import prolong_report
